source 'https://rubygems.org'
gem 'viddl-rb'
# gem 'streamio-ffmpeg'
# gem 'rmov', '~> 0.1.6'
# gem 'gstreamer'
gem 'awesome_print'
gem 'gemcutter', '~> 0.7.1'
gem 'vimeo'
gem 'watir-webdriver'
gem 'nokogiri'
gem 'activerecord'
gem 'mysql2'
gem 'rake'
gem 'builder', '~> 3.1.0'
gem 'echonest-ruby-api'
gem 'quiet_assets'